#include "wifi_station.h"

#include <stdio.h>
#include <string.h>

#include "esp_check.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_netif_ip_addr.h"
#include "esp_wifi.h"
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "nvs_flash.h"

#define WIFI_CONNECTED_BIT    BIT0
#define WIFI_FAIL_BIT         BIT1

static const char *TAG = "wifi_station";

static EventGroupHandle_t s_wifi_event_group = NULL;
static esp_event_handler_instance_t s_wifi_event_instance = NULL;
static esp_event_handler_instance_t s_ip_event_instance = NULL;
static int s_retry_count = 0;
static bool s_connected = false;
static bool s_initialized = false;
static char s_ip_address[WIFI_STATION_IP_STRING_LENGTH] = "0.0.0.0";

/**
 * @brief Initialize the NVS flash component required by the Wi-Fi driver.
 */
static esp_err_t wifi_station_initialize_nvs(void)
{
    esp_err_t result = nvs_flash_init();

    /*
     * Erase and recreate NVS when its stored format is incompatible with the
     * current firmware or when no free pages remain.
     */
    if (result == ESP_ERR_NVS_NO_FREE_PAGES ||
        result == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_RETURN_ON_ERROR(nvs_flash_erase(), TAG, "Failed to erase NVS");
        result = nvs_flash_init();
    }

    return result;
}

/**
 * @brief Handle Wi-Fi and IP events generated by ESP-IDF.
 */
static void wifi_station_event_handler(void *handler_argument,
                                       esp_event_base_t event_base,
                                       int32_t event_id,
                                       void *event_data)
{
    (void)handler_argument;

    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) {
        ESP_LOGI(TAG, "Wi-Fi station started; connecting to SSID '%s'",
                 WIFI_STATION_SSID);
        esp_wifi_connect();
        return;
    }

    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
        s_connected = false;
        snprintf(s_ip_address, sizeof(s_ip_address), "0.0.0.0");

        if (s_retry_count < WIFI_STATION_MAXIMUM_RETRY) {
            ++s_retry_count;
            ESP_LOGW(TAG,
                     "Disconnected from '%s'; retrying (%d/%d)",
                     WIFI_STATION_SSID,
                     s_retry_count,
                     WIFI_STATION_MAXIMUM_RETRY);
            esp_wifi_connect();
        } else {
            ESP_LOGE(TAG,
                     "Could not connect to '%s' after %d retries",
                     WIFI_STATION_SSID,
                     WIFI_STATION_MAXIMUM_RETRY);

            if (s_wifi_event_group != NULL) {
                xEventGroupSetBits(s_wifi_event_group, WIFI_FAIL_BIT);
            }
        }
        return;
    }

    if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        const ip_event_got_ip_t *event =
            (const ip_event_got_ip_t *)event_data;

        snprintf(s_ip_address,
                 sizeof(s_ip_address),
                 IPSTR,
                 IP2STR(&event->ip_info.ip));

        s_retry_count = 0;
        s_connected = true;

        ESP_LOGI(TAG, "Connected to SSID '%s'", WIFI_STATION_SSID);
        ESP_LOGI(TAG, "IPv4 address: %s", s_ip_address);

        if (s_wifi_event_group != NULL) {
            xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
        }
    }
}

/**
 * @brief Initialize ESP-NETIF, the default event loop, and the Wi-Fi driver.
 */
static esp_err_t wifi_station_initialize_stack(void)
{
    if (s_initialized) {
        return ESP_OK;
    }

    ESP_RETURN_ON_ERROR(wifi_station_initialize_nvs(),
                        TAG,
                        "NVS initialization failed");

    esp_err_t result = esp_netif_init();
    if (result != ESP_OK && result != ESP_ERR_INVALID_STATE) {
        ESP_LOGE(TAG, "ESP-NETIF initialization failed: %s",
                 esp_err_to_name(result));
        return result;
    }

    result = esp_event_loop_create_default();
    if (result != ESP_OK && result != ESP_ERR_INVALID_STATE) {
        ESP_LOGE(TAG, "Default event loop creation failed: %s",
                 esp_err_to_name(result));
        return result;
    }

    /*
     * Create and attach the default station network interface. The returned
     * interface is managed by ESP-IDF for the lifetime of this application.
     */
    esp_netif_t *station_netif = esp_netif_create_default_wifi_sta();
    if (station_netif == NULL) {
        ESP_LOGE(TAG, "Failed to create the default Wi-Fi station interface");
        return ESP_FAIL;
    }

    const wifi_init_config_t wifi_initialization = WIFI_INIT_CONFIG_DEFAULT();
    ESP_RETURN_ON_ERROR(esp_wifi_init(&wifi_initialization),
                        TAG,
                        "Wi-Fi driver initialization failed");

    s_wifi_event_group = xEventGroupCreate();
    if (s_wifi_event_group == NULL) {
        ESP_LOGE(TAG, "Failed to create the Wi-Fi event group");
        return ESP_ERR_NO_MEM;
    }

    ESP_RETURN_ON_ERROR(
        esp_event_handler_instance_register(WIFI_EVENT,
                                            ESP_EVENT_ANY_ID,
                                            &wifi_station_event_handler,
                                            NULL,
                                            &s_wifi_event_instance),
        TAG,
        "Failed to register the Wi-Fi event handler");

    ESP_RETURN_ON_ERROR(
        esp_event_handler_instance_register(IP_EVENT,
                                            IP_EVENT_STA_GOT_IP,
                                            &wifi_station_event_handler,
                                            NULL,
                                            &s_ip_event_instance),
        TAG,
        "Failed to register the IP event handler");

    s_initialized = true;
    return ESP_OK;
}

esp_err_t wifi_station_connect(char *ip_address, size_t ip_address_size)
{
    if (ip_address == NULL) {
        return ESP_ERR_INVALID_ARG;
    }

    if (ip_address_size < WIFI_STATION_IP_STRING_LENGTH) {
        return ESP_ERR_INVALID_SIZE;
    }

    ESP_RETURN_ON_ERROR(wifi_station_initialize_stack(),
                        TAG,
                        "Wi-Fi stack initialization failed");

    s_retry_count = 0;
    s_connected = false;
    snprintf(s_ip_address, sizeof(s_ip_address), "0.0.0.0");
    xEventGroupClearBits(s_wifi_event_group,
                         WIFI_CONNECTED_BIT | WIFI_FAIL_BIT);

    wifi_config_t wifi_configuration = {
        .sta = {
            .ssid = WIFI_STATION_SSID,
            .password = WIFI_STATION_PASSWORD,
            .threshold.authmode = WIFI_AUTH_WPA2_PSK,
            .pmf_cfg = {
                .capable = true,
                .required = false,
            },
        },
    };

    ESP_RETURN_ON_ERROR(esp_wifi_set_mode(WIFI_MODE_STA),
                        TAG,
                        "Failed to select station mode");

    ESP_RETURN_ON_ERROR(esp_wifi_set_config(WIFI_IF_STA,
                                            &wifi_configuration),
                        TAG,
                        "Failed to configure Wi-Fi credentials");

    ESP_RETURN_ON_ERROR(esp_wifi_start(),
                        TAG,
                        "Failed to start the Wi-Fi driver");

    /*
     * The event handler sets one of these bits after either receiving an IPv4
     * address or exhausting the reconnect attempts.
     */
    const EventBits_t event_bits =
        xEventGroupWaitBits(s_wifi_event_group,
                            WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
                            pdFALSE,
                            pdFALSE,
                            portMAX_DELAY);

    if ((event_bits & WIFI_CONNECTED_BIT) != 0U) {
        snprintf(ip_address, ip_address_size, "%s", s_ip_address);
        return ESP_OK;
    }

    snprintf(ip_address, ip_address_size, "0.0.0.0");
    return ESP_FAIL;
}

bool wifi_station_is_connected(void)
{
    return s_connected;
}

const char *wifi_station_get_ip_address(void)
{
    return s_ip_address;
}
